# Generated by Django 5.2.2 on 2025-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
